app:
  name: "chatgpt"
  llm:
    chat_history_limit: 2
    max_tokens: 2000
    model_name: deepseek-chat
    provider: deepseek
    stream: false
    temperature: 0.7
    system_prompt: "Перепиши исходный текст в заданном стиле."
  max_input_length: 15000
strings:
  ru:
    generation_menu: "Меню генерации контента 📝\n\nВыберите опцию ниже:"
    select_saved: "Выбрать сохраненный стиль 📋"
    create_style: "Создать новый стиль ✨"
    back_to_menu: "Назад в главное меню"
    back: "Назад"
    cancel: "Отмена"
    
    # Style-related strings
    no_styles: "У вас пока нет сохраненных стилей. Создайте новый стиль, чтобы начать."
    select_style: "Выберите стиль из списка ниже:"
    enter_style_examples_multiple: "Пожалуйста, отправьте примеры постов.\n\nВы можете отправить несколько сообщений - я буду использовать их для понимания стиля."
    enter_style_name: "Отлично! Теперь дайте название этому стилю:"
    enter_style_description: "Добавьте краткое описание для этого стиля (необязательно):"
    style_created: "Стиль '{name}' успешно создан! ✅"
    style_not_found: "Стиль не найден."
    example_added: "Пример успешно добавлен к стилю!"
    done: "Готово"
    
    # Post-related strings
    enter_post_content: "Вы выбрали стиль: {style_name}\n\nТеперь введите текст, который хотите отредактировать:"
    post_preview: "Вот ваш сгенерированный пост:"
    post_edited: "Вот ваш отредактированный пост:"
    post_updated: "Пост был обновлен:"
    post_published: "Ваш пост успешно опубликован! ✅"
    post_saved: "Ваш пост сохранен! ✅"
    post_scheduled: "Ваш пост запланирован к публикации в {time}! ⏰"
    post_not_found: "Пост не найден."
    invalid_date_format: "Неверный формат даты. Пожалуйста, используйте формат ГГГГ-ММ-ДД ЧЧ:ММ (например, 2025-03-20 14:30)"
    not_enough_balance: "У вас недостаточно средств для генерации поста. Пожалуйста, пополните баланс."
    please_wait: "Пожалуйста, подождите, пока я обрабатываю ваш запрос..."
    
    # Action buttons
    edit_post: "Редактировать с ИИ ✏️"
    publish_post: "Опубликовать сейчас 🚀"
    schedule_post: "Запланировать публикацию ⏰"
    manual_edit: "Редактировать вручную 📝"
    save_post: "Сохранить пост 💾"
    
    # Editing
    edit_post_manually: "Пожалуйста, отредактируйте текст ниже и отправьте обновленную версию:"
    enter_post_title: "Пожалуйста, введите заголовок для вашего поста:"
    enter_schedule_time: "Когда вы хотите запланировать этот пост? Пожалуйста, используйте формат ГГГГ-ММ-ДД ЧЧ:ММ (например, 2025-03-20 14:30)"

    # Posts list
    your_posts: "Ваши сохраненные посты:"
    no_posts: "У вас пока нет сохраненных постов."