strings:
  ru:
    start_message: |
      👋 Привет! Я — твой ИИ-помощник для создания постов!
      Я помогу тебе  автоматизировать рутину: редактирую и оформляю посты за тебя.
      Экономлю твоё время: даже сложные задачи решаю за минуты.
      Сокращаю расходы: больше не нужна команда редакторов! Нажмите /menu чтобы перейти в главное меню.
