strings:
  ru:
    message: |
      ✨ Как это работает?
      1️⃣ «Генерация по стилю»
      — Отправь 3-5 постов из канала → бот проанализирует стиль, который можно сохранить.
      — После этого новый пост можно отредактировать в этом же стиле.
      
      
      2️⃣ «Отредактировать ошибки»
      — Пришли текст → бот исправит орфографию и пунктуацию, сохранив оригинальный стиль.
      
      
      3️⃣ «Выбрать из сохраненных постов»
      — Все созданные в боте посты хранятся здесь.
      — Нажми кнопку → выбери нужный пост из списка → отправь в канал.
